export const GET_GIFTS 		= 'GET_GIFTS';
export const READ_GIFT 		= 'READ_GIFT';
export const GIFTS_LOADING  = 'GIFTS_LOADING';
/* Portfolio actiontypes */
export const GET_PORTFOLIOITEMS = "GET_PORTFOLIOITEMS";
export const GET_PORTFOLIOITEM = "GET_PORTFOLIOITEM";
export const PORTFOLIOITEMS_LOADING = "PORTFOLIOITEMS_LOADING";
export const ADD_PORTFOLIOITEM = "ADD_PORTFOLIOITEM";
export const EDIT_PORTFOLIOITEM = "EDIT_PORTFOLIOITEM";
export const DELETE_PORTFOLIOITEM = "DELETE_PORTFOLIOITEM";